### ISSUE TITLE
e. Testing: Spreadsheet Testing of forwarding/detection and avoidance

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/sfhw-proj2#13]
- [ ] #24
- [x] #25

**Comment by aidanfoss** [comment]
converted i and ii tasks into their own issues

**Comment by aidanfoss** [comment]
do you prefer this layout, or the layout of #26

**Comment by conneroisu** [comment]
I like it this way. Makes work split up more and makes progress more apparent while working on issues.

**Comment by conneroisu** [comment]
test
