### ISSUE TITLE
[2.b.ii] List which of these same instructions consume values, and what signals in the pipeline these correspond to.

### ISSUE THREAD

**Issue by aidanfoss** [conneroisu/sfhw-proj2#14]

**Comment by aidanfoss** [comment]
related to #13

**Comment by DanielMauricio13** [comment]
![image](https://github.com/user-attachments/assets/c1845d9d-3540-4855-b94f-523787033874)

**Comment by DanielMauricio13** [comment]
<img width="918" alt="Screenshot 2024-12-01 at 10 19 34 PM" src="https://github.com/user-attachments/assets/fd4ffcf2-c39e-4d6e-8c7a-a9046fbbd777">

**Comment by aidanfoss** [comment]
added to the report
