### ISSUE TITLE
[2.c.i]  list all instructions that may result in a non-sequential PC update and in which pipeline stage that update occurs.

### ISSUE THREAD

**Issue by aidanfoss** [conneroisu/sfhw-proj2#17]

**Comment by conneroisu** [comment]
Instructions that may result in a non-sequential PC update and the corresponding pipeline stage:

1. BNE (Branch on Not Equal)

   - Pipeline stage: Decode (ID)

2. BEQ (Branch on Equal)

   - Pipeline stage: Decode (ID)

3. J (Jump)

   - Pipeline stage: Decode (ID)

4. JAL (Jump and Link)

   - Pipeline stage: Decode (ID)

5. JR (Jump Register)
   - Pipeline stage: Decode (ID)

All these instructions update the PC in a non-sequential manner during the Decode (ID) stage of the pipeline.

**Comment by DanielMauricio13** [comment]
<img width="899" alt="Screenshot 2024-12-01 at 10 23 46 PM" src="https://github.com/user-attachments/assets/f91e1f37-8bcb-49b7-a693-997141da3984">

**Comment by aidanfoss** [comment]
replaced this in the report:
![image](https://github.com/user-attachments/assets/e23998b3-3db3-4d15-ae7d-d7e878bbfa6c)
