### ISSUE TITLE
Forwarding Unit

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/sfhw-proj2#27]
<sub><a href="https://huly.app/guest/cpre381?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJjZDAwNGU3Y2M1YTc4NTQyOTUzYWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViY29ubmVyLWNwcmUzODEtNjcyNTBhMGUtNWMwM2NlOGY1Zi02YmU0NzMifQ.uRi4Vlc80niAl2YAZ2gE5uMOxUjoqWDF3tyrZMnBvaA">Huly&reg;: <b>PROJE-27</b></a></sub>

**Comment by aidanfoss** [comment]
You finished this Nov 21 with commit [d1ecebd](https://github.com/conneroisu/sfhw-proj2/commit/d1ecebdaf7bdc93690741fc78585855fa05ee31b)
