### ISSUE TITLE
Stage3 (EX/MEM)

### ISSUE THREAD

**Issue by aidanfoss** [conneroisu/sfhw-proj2#28]
<sub><a href="https://huly.app/guest/cpre381?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJjZDJmMWU3Y2M1YTc4NTQyOTUzZmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViY29ubmVyLWNwcmUzODEtNjcyNTBhMGUtNWMwM2NlOGY1Zi02YmU0NzMifQ.k06MNb382OXvBPXSVD06IVlH7Fxoaj7RiEQIGyuK_GM">Huly&reg;: <b>PROJE-28</b></a></sub>

**Comment by DanielMauricio13** [comment]
MEm/WB

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/d51d7c4a-11af-47d8-b9a6-4ecefaeb151f)
Is the branch missing from this stage currently? @DanielMauricio13

**Comment by DanielMauricio13** [comment]
it has been updated, almost a new file

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/3136390d-fe11-42fe-826e-5c8535ebd314)
![image](https://github.com/user-attachments/assets/6912cb22-57cc-4146-83d3-358b10813a01)
@DanielMauricio13

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/ff390dff-d352-4c40-9266-47189a2174d6)
![image](https://github.com/user-attachments/assets/abd7ae1f-0e64-4a7f-8372-6ca29deed4d8)

seems like test cases are passing, is there supposed to be those three null values? are those just passes and untested?
@DanielMauricio13
