### ISSUE TITLE
[1.a] Come up with a global list of the datapath values and control signals that are required during each pipeline stage.

### ISSUE THREAD

**Issue by aidanfoss** [conneroisu/sfhw-proj2#4]
Related to #3

**Comment by aidanfoss** [comment]
this seems deceptively difficult - seems like an extremely important first step that will be very difficult

**Comment by conneroisu** [comment]
| Signal name |                                        Effect when deasserted                                        |                                                    Effect when asserted                                                    |
| :---------: | :--------------------------------------------------------------------------------------------------: | :------------------------------------------------------------------------------------------------------------------------: |
|   RegDst    | The register file destination number for the Write <br> register comes from the $\mathrm{rt}$ field. |                 The register file destination number for the Write register comes from the <br> rd field.                  |
|  RegWrite   |                                                None.                                                 | The general-purpose register selected by the Write register number is <br> written with the value of the Write data input. |
|   ALUSrCA   |                                   The first ALU operand is the PC.                                   |                                      The first ALU operand comes from the A register.                                      |
|   MemRead   |                                                None.                                                 |            Content of memory at the location specified by the Address input is put <br> on Memory data output.             |
|  MemWrite   |                                                None.                                                 |   Memory contents at the location specified by the Address input is <br> replaced by the value on the Write data input.    |
|  MemtoReg   |             The value fed to the register file Write data input <br> comes from ALUOut.              |                          The value fed to the register file Write data input comes from the MDR.                           |
|    IorD     |                    The PC is used to supply the address to the <br> memory unit.                     |                                  ALUOut is used to supply the address to the memory unit.                                  |
|   IRWrite   |                                                None.                                                 |                                      The output of the memory is written into the IR.                                      |
|   PCWrite   |                                                None.                                                 |                                  The PC is written; the source is controlled by PCSource.                                  |
| PCWriteCond |                                                None.                                                 |                           The PC is written if the Zero output from the ALU is also active.<br>                            |

| Signal name | Value (binary) |                                                              Effect                                                              |
| :---------: | :------------: | :------------------------------------------------------------------------------------------------------------------------------: |
|    ALUOp    |       00       |                                                The ALU performs an add operation.                                                |
|             |       01       |                                              The ALU performs a subtract operation.                                              |
|             |       10       |                                 The funct field of the instruction determines the ALU operation.                                 |
|   ALUSrcB   |       00       |                                      The second input to the ALU comes from the B register.                                      |
|             |       01       |                                          The second input to the ALU is the constant 4.                                          |
|             |       10       |                            The second input to the ALU is the sign-extended, lower 16 bits of the IR.                            |
|             |       11       |               The second input to the ALU is the sign-extended, lower 16 bits of the IR shifted left <br> 2 bits.                |
|  PCSource   |       00       |                                    Output of the ALU $(P C+4)$ is sent to the PC for writing.                                    |
|             |       01       |                        The contents of ALUOut (the branch target address) are sent to the PC for writing.                        |
|             |       10       | The jump target address (IR[25:0] shifted left 2 bits and concatenated with <br> PC $+4[31: 28])$ is sent to the PC for writing. |

**Comment by conneroisu** [comment]
![image](https://github.com/user-attachments/assets/a2cdff1c-80ef-4668-b103-4f78efa6c058)

**Comment by conneroisu** [comment]
Check out the document in the diagram:
https://app.eraser.io/workspace/ONdQZqJ8JixF0Aaz8n6M

**Comment by conneroisu** [comment]
Forwarding Unit:
Signals Needed:

ID/EX.RegisterRs: The source register Rs of the instruction in the EX stage (for operand A).
ID/EX.RegisterRt: The source register Rt of the instruction in the EX stage (for operand B).
EX/MEM.WriteReg: The destination register of the instruction in the MEM stage (could be Rd or Rt depending on instruction type).
EX/MEM.RegWrite: A control signal indicating whether the instruction in the MEM stage writes to a register.
MEM/WB.WriteReg: The destination register of the instruction in the WB stage (could be Rd or Rt depending on instruction type).
MEM/WB.RegWrite: A control signal indicating whether the instruction in the WB stage writes to a register.
