### ISSUE TITLE
[1.c.iii] Include an annotated waveform in your writeup of two iterations or recursions of these programs executing correctly and provide a short discussion of result correctness. In your waveform and annotation, provide 3 different examples (at least one data-flow and one control-flow) of where you did not have to use the maximum number of NOPs.

### ISSUE THREAD

**Issue by aidanfoss** [conneroisu/sfhw-proj2#8]
[For teams with >4]

**Comment by conneroisu** [comment]
Probably need to touch on how we could improve here. Here are some ideas I have right now:
Two issue datapath implementation:
![image](https://github.com/user-attachments/assets/3ef95c96-9b28-43c8-bef6-44ad9b351d74)
 The additions needed for double issue are highlighted: another 32 bits from instruction memory, two more read ports and one more write port on the register file, and another ALU. Assume the bottom ALU handles address calculations for data transfers and the top ALU handles everything else.

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/73a431d2-a5e2-4a96-b987-c5ebcf035fe1)
